import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { examples } from '../shared/examples';
import { VERSION, documentSchema, newWorkspace, parseDocument, type ReadingDocument, type Workspace } from '../shared/model';
import { readLibrary, writeLibrary, download } from './storage';
import { Reading, WaterIllustration } from './Content';
import { exportHtml } from '../shared/export';
import { request } from './api';
const Editor = lazy(() => import('./Editor'));
const Account = lazy(() => import('./Account'));
function initialLibrary() { try { return { library: readLibrary(), error: '' }; } catch { return { library: {}, error: 'Não foi possível recuperar os projetos locais. Não gravaremos sobre eles. Exporte o armazenamento para recuperação antes de continuar.' }; } }

export default function App() {
  const [initial] = useState(initialLibrary);
  const [library, setLibrary] = useState<Record<string, Workspace>>(initial.library);
  const [storageError, setStorageError] = useState(initial.error);
  const [route, setRoute] = useState(location.hash.slice(1) || '/');
  const [status, setStatus] = useState(''); const [error, setError] = useState('');
  const [publicDoc, setPublicDoc] = useState<ReadingDocument | null>(null);
  const [loading, setLoading] = useState(false); const [retry, setRetry] = useState(0);
  const main = useRef<HTMLElement>(null); const previousRoute = useRef(route);
  const [confirmReset, setConfirmReset] = useState<string | null>(null);
  const routeParts = route.split('?')[0].split('/');
  const page = routeParts[1]; const id = routeParts[2];
  const current = id ? library[id] : undefined;
  function announce(s: string) { setStatus(''); setTimeout(() => setStatus(s), 10); }
  useEffect(() => { const listener = () => { setRoute(location.hash.slice(1) || '/'); setError(''); }; window.addEventListener('hashchange', listener); return () => window.removeEventListener('hashchange', listener); }, []);
  useEffect(() => {
    document.title = `${current?.document.title || ({ projects: 'Meus projetos', about: 'Sobre o projeto', help: 'Ajuda e acessibilidade', published: 'Leitura publicada' }[page] || 'Caminhos para uma leitura acessível')} — WABlind`;
    if (previousRoute.current !== route) main.current?.focus();
    previousRoute.current = route;
  }, [route]);
  useEffect(() => {
    if (page !== 'published' || !id) return;
    let active = true; setPublicDoc(null); setLoading(true); setError('');
    request<{ document: ReadingDocument }>(`/publications/${encodeURIComponent(id)}`, 'GET', undefined, false).then(data => { if (active) setPublicDoc(documentSchema.parse(data.document)); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [route, retry]);
  function persist(w: Workspace) {
    if (!w.revisions.length && !w.document.annotations.length && library[w.document.id]) {
      try { sessionStorage.removeItem(`wablind.form-drafts.${w.document.id}`); } catch { /* Export remains available when browser storage is restricted. */ }
    }
    const next = { ...library, [w.document.id]: w }; setLibrary(next);
    if (initial.error) return;
    try { writeLibrary(next); setStorageError(''); } catch { setStorageError('Não foi possível gravar neste navegador. Mantenha a página aberta e exporte o JSON do seu trabalho.'); }
  }
  function start(doc: ReadingDocument, fresh = false) {
    if (fresh || !library[doc.id]) persist(newWorkspace(doc));
    location.hash = '/edit/' + doc.id;
  }
  function openRemote(w: Workspace) {
    const old = library[w.document.id];
    if (old && JSON.stringify(old.document) !== JSON.stringify(old.savedDocument)) {
      const copy = structuredClone(old); copy.document.id = crypto.randomUUID(); delete copy.remoteId; delete copy.remoteVersion; delete copy.ownerId;
      const next = { ...library, [copy.document.id]: copy, [w.document.id]: w }; setLibrary(next);
      try { writeLibrary(next); } catch { setStorageError('O armazenamento local está cheio. Exporte seu trabalho.'); }
      announce('O rascunho anterior foi preservado como cópia local.');
    } else persist(w);
    location.hash = '/edit/' + w.document.id;
  }
  const readingDoc = page === 'published' ? publicDoc : page === 'snapshot' ? current?.publication : current?.document;
  return <>
    <a className="skip-link" href="#main" onClick={e => { e.preventDefault(); main.current?.focus(); }}>Ir para o conteúdo principal</a>
    <header className="site-header"><a className="brand" href="#/" aria-label="WABlind, início"><span className="brand-symbol" aria-hidden="true">w<span>•</span></span><span>WA<span className="brand-light">Blind</span><small>ACESSO COM CONTEXTO</small></span></a><nav aria-label="Navegação principal"><a href="#/" aria-current={!page ? 'page' : undefined}>Explorar</a><a href="#/projects" aria-current={page === 'projects' ? 'page' : undefined}>Meus projetos</a><a href="#/about" aria-current={page === 'about' ? 'page' : undefined}>Sobre</a><a href="#/help" aria-current={page === 'help' ? 'page' : undefined}>Ajuda</a></nav><span className="beta-tag">BETA 2.0</span></header>
    <div className="status-region" role="status" aria-live="polite">{status}</div>
    <main id="main" ref={main} tabIndex={-1}>
      {storageError && <div className="error" role="alert"><p>{storageError}</p><button onClick={() => download('wablind-recuperacao.json', localStorage.getItem('wablind.workspace.v1') || '{}', 'application/json')}>Exportar armazenamento para recuperação</button></div>}
      {error && <p className="error" role="alert">{error}</p>}
      {!page && <>
        <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-line" /> TECNOLOGIA + MEDIAÇÃO HUMANA</p><h1>Todo conteúdo merece<br />um caminho de <em>acesso.</em></h1><p className="hero-description">Explore, descreva e organize conteúdos educativos. Transforme sua mediação em uma leitura com mais contexto — e com a pessoa no centro.</p><div className="actions"><a className="button primary" href="#examples" onClick={e => { e.preventDefault(); document.getElementById('examples')?.scrollIntoView(); document.getElementById('examples-title')?.focus(); }}>Experimentar a WABlind <span aria-hidden="true">↗</span></a><a className="quiet-link" href="#/about">Conheça o projeto <span aria-hidden="true">→</span></a></div><p className="hero-note">Sem cadastro para explorar. Sem automação decidindo por você.</p></div><div className="hero-art" aria-label="Exemplo de uma descrição contextual"><div className="art-top"><span className="dot" /><span>UMA VIAGEM COM A ÁGUA</span><span>01 / 03</span></div><WaterIllustration description="O Sol aquece a água do rio; setas representam a evaporação e o retorno como chuva." /><div className="art-note"><span className="annotation-label">DESCRIÇÃO COM CONTEXTO</span><p>O Sol aquece a água do rio. Ela sobe como vapor e retorna à superfície na forma de chuva.</p><span className="small">✓ Uma contribuição humana para a leitura</span></div><span className="art-caption">O detalhe que você descreve abre um novo caminho.</span></div></section>
        <section className="principles" aria-label="Como funciona"><div><span>01</span><p><strong>Escolha um conteúdo</strong>Comece com um exemplo pronto.</p></div><div><span>02</span><p><strong>Acrescente contexto</strong>Use marcadores e descrições.</p></div><div><span>03</span><p><strong>Prepare a leitura</strong>Revise, salve e exporte.</p></div></section>
        <section id="examples" className="examples-section"><div className="section-heading"><div><p className="eyebrow">APRENDER EXPERIMENTANDO</p><h2 id="examples-title" tabIndex={-1}>Por onde vamos começar?</h2></div><p>Três pequenos percursos para conhecer<br />as possibilidades da mediação.</p></div><div className="example-grid">{examples.map((item, index) => <article className={`example-card example-${index}`} key={item.document.id}><div className="card-top"><span className="eyebrow">{item.tag}</span><span className="card-number">0{index + 1}</span></div><h3>{item.document.title}</h3><p>{item.summary}</p><div className="card-bottom"><span>{item.duration}</span><button onClick={() => start(item.document)} aria-label={`Explorar: ${item.document.title}`}>Explorar <span aria-hidden="true">↗</span></button></div></article>)}</div><p className="small muted">Materiais demonstrativos originais. Suas alterações ficam neste navegador até serem exportadas ou enviadas a um projeto conectado.</p></section>
        <section className="research-strip"><span className="research-year">2018 <span>→</span> hoje</span><div><h2>Uma trajetória de pesquisa. Uma ferramenta em movimento.</h2><p>A WABlind nasceu do estudo sobre acessibilidade e comunicabilidade de conteúdo web mediado. Esta atualização preserva sua proposta e renova a experiência.</p></div><a href="#/about">Da pesquisa à prática <span aria-hidden="true">↗</span></a></section>
      </>}
      {page === 'projects' && <><div className="page-heading"><p className="eyebrow">ESPAÇO DE MEDIAÇÃO</p><h1>Meus projetos</h1><p>Retome suas leituras e mantenha suas contribuições por perto.</p></div><section className="local-projects"><h2>Neste navegador</h2>{Object.values(library).length ? <ul className="project-list">{Object.values(library).map(w => <li key={w.document.id}><div><h3>{w.document.title}</h3><p>{w.document.annotations.length} marcações · {w.revisions.length} revisões · {w.remoteId ? 'cópia de projeto conectado' : 'local'}</p></div><div className="actions"><a className="button" href={`#/edit/${w.document.id}`}>Continuar edição</a><button onClick={() => setConfirmReset(w.document.id)}>Reiniciar</button></div>{confirmReset === w.document.id && <div className="reset-confirm"><p>Reiniciar remove as marcações e revisões desta cópia local. O projeto no serviço não será alterado. Exporte o JSON antes, se precisar guardá-lo.</p><button className="danger" onClick={() => { const original = examples.find(e => e.document.id === w.document.id)?.document || { ...w.document, annotations: [] }; persist(newWorkspace(original)); setConfirmReset(null); announce('Cópia local reiniciada.'); }}>Confirmar reinício local</button><button onClick={() => setConfirmReset(null)}>Cancelar</button></div>}</li>)}</ul> : <div className="empty-state"><h3>Seu primeiro percurso começa aqui.</h3><p>Escolha um exemplo ou importe um arquivo que você já exportou.</p><a className="button primary" href="#/">Explorar exemplos</a></div>}<div className="import-file"><label htmlFor="import-json">Reimportar projeto JSON <span className="muted">(até 5 MB)</span></label><input id="import-json" type="file" accept="application/json,.json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 5 * 1024 * 1024) throw new Error('O arquivo excede 5 MB.'); const doc = parseDocument(await file.text()); doc.id = crypto.randomUUID(); start(doc, true); announce('Arquivo importado como nova cópia local.'); } catch (e) { setError((e as Error).message); } }} /></div></section><Suspense fallback={<p role="status">Carregando área conectada…</p>}><Account open={openRemote} announce={announce} /></Suspense></>}
      {page === 'edit' && (current ? <Suspense fallback={<p role="status">Carregando editor…</p>}><Editor key={id} workspace={current} update={persist} announce={announce} /></Suspense> : <Missing />)}
      {['read', 'snapshot', 'published'].includes(page) && <>{loading ? <p role="status">Carregando leitura…</p> : readingDoc ? <><div className="reader-toolbar"><a href={page === 'published' ? '#/' : `#/edit/${id}`}>← {page === 'published' ? 'Explorar a WABlind' : 'Voltar à edição'}</a><span>{page === 'published' ? 'Publicação' : page === 'snapshot' ? 'Revisão preparada · somente local' : 'Prévia do rascunho · somente local'}</span><button onClick={() => download(`${readingDoc.id}.html`, exportHtml(readingDoc), 'text/html')}>Exportar HTML</button></div><Reading document={readingDoc} /></> : page === 'published' ? <div className="empty-state"><h1>Leitura não disponível</h1><p>A publicação pode ter sido retirada ou o serviço pode estar indisponível.</p><button onClick={() => setRetry(v => v + 1)}>Tentar novamente</button><a className="inline-link" href="#/">Explorar os exemplos locais</a></div> : <Missing />}</>}
      {page === 'about' && <article className="prose"><p className="eyebrow">PESQUISA QUE CONTINUA</p><h1>Acesso não é só chegar.<br />É poder compreender.</h1><p className="lead">A WABlind combina apoio técnico e mediação humana para organizar conteúdos web e acrescentar descrições relevantes ao contexto educativo.</p><h2>De onde viemos</h2><p>A proposta foi apresentada no artigo “Avaliação da Comunicabilidade da WABlind em Enciclopédias On-line”, de Natacsha Ordones Raposo, Alberto Castro e Thais Castro, publicado no SBIE em 2018.</p><p>O estudo examinou a comunicabilidade com professores. Os achados orientam esta atualização: seleção explícita, marcadores explicados, acompanhamento de contribuições e revisão antes da publicação.</p><p><a href="https://doi.org/10.5753/cbie.sbie.2018.1153">Consultar o artigo original ↗</a></p><h2>O que estamos atualizando</h2><p>Uma aplicação da trajetória de pesquisa de Natacsha, agora preparada para o portfólio de aplicações desenvolvidas. O projeto se relaciona à organização e ao uso contextualizado do conhecimento de acessibilidade, sem integrar automaticamente a MADO ou acrescentar uma nova avaliação à tese.</p><h2>O que esta versão não promete</h2><p>A WABlind não torna qualquer site automaticamente acessível. Não inventa descrições, não decide a relevância pedagógica por você e não comprova conformidade por contagem de alertas. Os resultados de 2018 não são resultados desta versão.</p><div className="notice"><strong>Versão {VERSION}</strong><p>Demonstração local independente. Recursos conectados dependem da configuração de serviços externos. Não houve nova avaliação com participantes nesta entrega.</p></div><h2>Autoria e procedência</h2><p>Projeto da trajetória de pesquisa de Natacsha. Os exemplos atuais são materiais demonstrativos originais; não reproduzem dados de estudantes ou participantes. Os créditos e direitos das fontes importadas devem ser preservados.</p></article>}
      {page === 'help' && <article className="prose"><p className="eyebrow">AJUDA E ACESSIBILIDADE</p><h1>Você tem o controle.</h1><h2>Como preparar uma leitura</h2><ol><li>Abra um exemplo na página Explorar.</li><li>Selecione um elemento na lista ou use “Marcar trecho”.</li><li>Escolha um tipo, escreva a descrição e aplique a marcação.</li><li>Salve uma revisão e abra a prévia da leitura.</li><li>Exporte HTML para ler ou JSON para continuar a edição depois.</li></ol><h2>Usar pelo teclado</h2><p>Use Tab e Shift+Tab para percorrer os controles. Ative botões com Enter ou Espaço. O link “Ir para o conteúdo principal” pula a navegação. Não é necessário arrastar elementos nem usar o botão direito do mouse.</p><h2>O que é salvo</h2><p>O rascunho é recuperável neste navegador quando o armazenamento local está disponível. “Salvar revisão” cria um ponto no histórico. “Publicar” disponibiliza uma revisão conectada e não acontece automaticamente. Limpar os dados do navegador pode apagar projetos locais: exporte uma cópia JSON.</p><h2>Privacidade</h2><p>Não insira dados pessoais de estudantes. A demonstração não envia seu conteúdo a um servidor. Nos projetos conectados, conteúdo e contribuições são enviados aos serviços configurados; rascunhos são privados e somente a proprietária publica. Imagens remotas não são carregadas diretamente no seu navegador durante a captura.</p><h2>Limites da importação</h2><p>São aceitas páginas HTML públicas em domínios habilitados. Scripts, formulários e conteúdo ativo não são executados. Elementos não suportados são sinalizados. A adaptação não modifica a fonte.</p><h2>Estado de acessibilidade</h2><p>Projetada para WCAG 2.2 AA, com HTML semântico, operação por teclado e comunicação textual dos estados. Não há declaração de conformidade. Os testes automatizados não substituem avaliação com leitores de tela e pessoas com deficiência.</p><h2>Encontrou uma barreira?</h2><p>Registre a página, o controle, o que esperava e o que aconteceu. Informe navegador e tecnologia assistiva, sem incluir dados pessoais ou conteúdo privado.</p><a href="https://github.com/natacsham" rel="noreferrer">Perfil da autora no GitHub ↗</a></article>}
      {page && !['projects', 'edit', 'read', 'snapshot', 'published', 'about', 'help'].includes(page) && <Missing />}
    </main>
    <footer className="site-footer"><div><a className="footer-brand" href="#/">WABlind</a><p>Conhecimento compartilhado.<br />Acesso construído em conjunto.</p></div><div><a href="#/about">Sobre o projeto</a><a href="#/help">Ajuda e acessibilidade</a><a href="https://doi.org/10.5753/cbie.sbie.2018.1153">Artigo de 2018 ↗</a></div><p className="footer-note">Uma aplicação da trajetória de pesquisa de Natacsha.<br />{VERSION} · Mediação humana, sempre.</p></footer>
  </>;
}
function Missing() { return <div className="empty-state"><h1>Projeto não encontrado neste navegador</h1><p>Retome um projeto salvo, reimporte seu JSON ou explore um exemplo.</p><a href="#/projects" className="button primary">Abrir meus projetos</a></div>; }
