import { VERSION } from '../shared/model';

export function History() {
  return <article className="prose history-page">
    <p className="eyebrow">TRAJETÓRIA DE PESQUISA E DESENVOLVIMENTO</p>
    <h1>A evolução da WABlind</h1>
    <p className="lead">A edição de uma página continua no centro. A mediação agora também explicita a tarefa, a função dos elementos e as relações entre formas de apresentação.</p>
    <div className="history-stages"><section><p className="eyebrow">ORIGEM</p><h2>Acesso web com mediação humana</h2><p>A WABlind foi desenvolvida para apoiar o acesso de pessoas cegas a conteúdos web. Sua proposta combinava tratamento técnico da página e marcações feitas por professores ou mediadores, considerando a relevância pedagógica do conteúdo.</p><p>O professor informava uma URL, selecionava elementos e associava marcadores. A versão preparada podia ser encontrada para leitura a partir da fonte.</p></section>
      <section><p className="eyebrow">CONTINUIDADE</p><h2>Selecionar, classificar e contextualizar</h2><p>A evolução preserva a seleção de títulos, textos, imagens, listas, tabelas e referências. A marcação passa a registrar também para que o elemento serve na atividade e por que uma transformação foi escolhida.</p><p>Sínteses e explicações são contribuições elaboradas e revisadas pelo professor. A captura original e a autoria da fonte permanecem distintas dessas contribuições.</p></section>
      <section><p className="eyebrow">PROPOSTA ATUAL</p><h2>Relações multimodais examináveis</h2><p>Multimodalidade envolve articular modos para uma finalidade e uma situação de interação. Descrever um gráfico, apresentar dados em tabela e orientar uma comparação podem cumprir funções complementares, alternativas ou sequenciais.</p><p>Disponibilizar texto e áudio, por si só, não demonstra que a tarefa foi apoiada. O professor registra funções, condições e justificativas; o leitor conhece as relações e mantém controle sobre sua exploração.</p></section></div>
    <h2>O que a história permite afirmar</h2><p>O artigo de 2018 relata uma avaliação de comunicabilidade com professores. Seus achados orientam a clareza da seleção, a escolha dos marcadores e o acompanhamento das contribuições. O trabalho documenta marcações de menu principal, área de pesquisa e descrição de imagens e vídeos. Esses resultados pertencem à versão e ao estudo históricos.</p><p>No legado, síntese de voz designava leitura por voz. A síntese textual autoral opcional é uma possibilidade desta evolução e não deve ser confundida com um resultado demonstrado naquele estudo.</p><p>A versão atual é uma reconstrução de software em desenvolvimento. Seus testes técnicos não reproduzem a avaliação histórica nem constituem nova validação do Arcabouço Multimodal ou da tese. O relatório técnico RT-GSI-2018-005 registra verificações automáticas históricas, não conformidade desta implementação.</p>
    <h2>Fontes e limites</h2><p>A aplicação identifica fonte, autoria conhecida, data de captura e responsável pela mediação. A captura externa depende de domínios habilitados e de condições de reutilização registradas. Sínteses ou alterações não tornam automaticamente permitida a reprodução de uma obra.</p><p>Os exemplos incluídos são materiais próprios demonstrativos, com situações e dados fictícios. Não representam participantes nem resultados de pesquisa. Algumas páginas e recursos dinâmicos não são compatíveis com a captura.</p>
    <h2>Autoria e referências</h2><p>Natacsha Melo · Universidade Federal do Amazonas (UFAM) · Programa de Pós-Graduação em Informática (PPGI).</p><p>Raposo, Natacsha; Castro, Thais; Castro, Alberto. <cite>Avaliação da Comunicabilidade da WABlind em Enciclopédias On-line</cite>. SBIE, 2018, p. 1153–1162. <a href="https://doi.org/10.5753/cbie.sbie.2018.1153" rel="noreferrer">Identificador DOI do artigo: 10.5753/cbie.sbie.2018.1153</a>.</p><p><cite>Teste de Conformidade da Ferramenta WABlind – Primeira Versão</cite>. Relatório técnico RT-GSI-2018-005, abril de 2018.</p><p className="muted">Versão {VERSION}. WABlind permanece como nome provisório desta evolução. As contribuições e decisões são revisáveis.</p>
    <a className="button" href="#/">Voltar à busca</a>
  </article>;
}

export function Help() {
  return <article className="prose"><p className="eyebrow">AJUDA E ACESSIBILIDADE</p><h1>Encontre, prepare e explore uma leitura</h1>
    <h2>Para quem vai ler</h2><p>Digite o endereço de uma página ou um assunto na busca. As sugestões mostram os recursos preparados e publicados. Use as setas para escolher e Enter para abrir; Escape fecha as sugestões. A leitura abre nesta mesma aba.</p><p>O botão com microfone permite ditar quando o navegador oferece esse recurso. A fala não abre um resultado sozinha: confira a transcrição e selecione Buscar. Você também pode digitar, usar teclado, toque ou ponteiro.</p>
    <h2>Durante a leitura</h2><p>A fonte e o responsável pela mediação aparecem antes do conteúdo. Use o índice para explorar seções e as representações relacionadas para conhecer seus propósitos e condições. O controle Ouvir leitura pode iniciar, pausar, continuar e parar a fala; ele não substitui seu leitor de tela.</p><p>As opções de tamanho e espaçamento do texto são preferências locais. Nenhum áudio começa automaticamente. Sínteses são opcionais e as omissões são identificadas.</p>
    <h2>Para professores</h2><ol><li>Entre na Área do professor com a conta fornecida pela administradora.</li><li>Informe uma URL habilitada e a condição de uso da fonte. A página será carregada automaticamente.</li><li>Defina tarefa, objetivo e responsável. Selecione elementos na página ou na lista equivalente.</li><li>Classifique, explique a função na atividade e escolha como apresentar. Acrescente representações relacionadas quando necessário.</li><li>Revise, salve e use Publicar para disponibilizar uma revisão específica. Salvar um rascunho não altera uma publicação anterior.</li></ol>
    <h2>Demonstração sem conta</h2><p><a href="#/examples">Experimente os materiais demonstrativos próprios</a>. As alterações e leituras preparadas ficam somente neste navegador. Elas não são publicações na internet. A demonstração funciona sem depender do serviço de captura.</p>
    <h2>Teclado, foco e limitações</h2><p>Use Tab e Shift+Tab para percorrer controles, Enter para links e Enter ou Espaço para botões. Na busca, Ctrl+K (ou Command+K) retorna ao campo. Ao navegar, o foco acompanha o novo conteúdo. O editor também oferece uma lista de elementos e alternativa estruturada à seleção visual.</p><p>O objetivo da interface é atender WCAG 2.2 AA. Não declaramos conformidade integral com base em verificadores automáticos. Reconhecimento e síntese de voz dependem do navegador; páginas externas podem exigir revisão humana de descrição, cabeçalhos e ordem de leitura.</p>
    <h2>Relatar um problema</h2><p>Na demonstração, registre a tela ou URL, o que tentou fazer, o que aconteceu e o navegador ou tecnologia assistiva utilizada. Entregue essas informações à professora ou à administradora que disponibilizou a WABlind. Não inclua senhas ou dados de estudantes.</p>
    <a href="#/" className="button">Voltar à busca</a>
  </article>;
}
